services:
  redis:
    image: redis:7-alpine
    container_name: momentum-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momentum-webapi
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      Redis__ConnectionString: "redis:6379"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=momentum_dev;Username=postgres;Password=postgres"
      EmailSettings__Host: "${EMAIL_HOST:-smtp.mail.ru}"
      EmailSettings__Port: "${EMAIL_PORT:-587}"
      EmailSettings__UseSsl: "${EMAIL_USE_SSL:-false}"
      EmailSettings__UserName: "${EMAIL_USERNAME:?EMAIL_USERNAME is required}"
      EmailSettings__Password: "${EMAIL_PASSWORD:?EMAIL_PASSWORD is required}"
      EmailSettings__FromEmail: "${EMAIL_FROM_EMAIL:?EMAIL_FROM_EMAIL is required}"
      EmailSettings__FromName: "${EMAIL_FROM_NAME:-Momentum}"
    depends_on:
      - redis
      - postgres
        
  postgres:
    image: postgres:18-alpine3.22
    container_name: momentum-postgres
    environment:
      POSTGRES_DB: momentum_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
